### PR TITLE
solve issue #1158 (enabling Right-to-Left fonts)

### LINKED ISSUE #1158: BitmapText right to left line wrapping not work
Line wrapping of a right to left text should be handled differently than left to right text. BitmapText wraps the right to left text in the same way it does for the left to right text.

See the forum for more info: 
https://hub.jmonkeyengine.org/t/how-to-display-a-right-to-left-text-with-wrap-mode-with-bitmaptext/42148

### PR DESCRIPTION
**Pull request by Aufricer**
This pull request is solving the problem with displaying Right to Left texts in JME. fixes #1158 and would also make the additional file for testcase close #1159 unnecessary.

More info could be found in the [forum  ](https://hub.jmonkeyengine.org/t/issue-with-line-wrapping-of-right-to-left-text-in-bitmaptext/42148/5) or in the discussion for issue #1158.

What changed: 
Beside repairing the behaviour of RtL texts, a new parameter in BitMapfont allowing to set the textdirection in the font and in Bitmaptext. Before that was not possible in the font itself. 
An interface "GlyphParser" now allowing the user  of Persian, Arabic or other RtL oriented fonts to use individual parsers for the correct position of letters in a text (that may differ depending on letter before or after that) something that is not needed for  Left to Rights texts.
Also a new discovered bug that brings different results for linewidth from BitmapText.getLineWidth() and BitmapFont.getLineWidth() for textinput with multilines had been fixed.

We have tested it and feel the PR is ready for review.

Edit: Of course it is Right to Left texts (at least I wrote it wrong on each occasion in the text)

### CODE REVIEW

**Comment by pspeed42** [comment]
Did you mean "Right to Left" in the above?

**Comment by stephengold** [comment]
I appreciate the hard work that went into this PR. Thank you for contributing to the project!

**Comment by Aufricer** [comment]
@pspeed42 - Yes of course. Right to Left texts...

**Comment by stephengold** [comment]
Why was the "local.properties" file deleted?

@pspeed42 Do you have any desire to review this PR?

**Comment by pspeed42** [comment]
I should probably give it a glance at least.

**Comment by Aufricer** [comment]
> Why was the "local.properties" file deleted?

I realized it was added by my JDK. It contained a warning saying remove before publishing and contained system info of the computer I had used.

**Comment by stephengold** [comment]
> I should probably give it a glance at least.

Will you have time to do so during the next 10 days?

**Comment by stephengold** [comment]
> > Why was the "local.properties" file deleted?
> 
> I realized it was added by my JDK. It contained a warning saying remove before publishing and contained system info of the computer I had used.

"local.properties" has been part of the Engine since 2015. I'm unsure what it does, but if it doesn't relate to this PR, please restore it.

**Comment by Aufricer** [comment]
I (hope) I have just restored the local.properties

File: jme3-core/src/main/java/com/jme3/font/Letters.java [hunk 1]
```diff
@@ -188,42 +194,66 @@ void update() {
...
-        cursor.setEndOfLine();
-        final float width = block.getTextBox().width;
-        final float height = block.getTextBox().height;
         float lineWidth = 0;
         float gapX = 0;
         float gapY = 0;
+
+        // Without a textblock there is no alignment
+        // For Left to Right texts the letters will simply be shown starting from left
+        // as linelenght is considered to be Integer.Maxvalue width
```
Comment (stephengold) [inline jme3-core/src/main/java/com/jme3/font/Letters.java:203]: linelenght -> line length
Integer.Maxvalue width -> infinite.

File: jme3-core/src/main/java/com/jme3/font/Letters.java [hunk 2]
```diff
@@ -188,42 +194,66 @@ void update() {
...
                 }
+                cursor.setAlignment(gapX, gapY);
+                cursor = cursor.getPrevious();
+            }
+        } else { // right to left
+            if ((alignment == Align.Right && valignment == VAlign.Top)) return;
+            LetterQuad cursor = tail.getPrevious();
+            gapX = (cursor.getX0()-block.getTextBox().x)*-1;
+            if (alignment == Align.Center) gapX = gapX/2; // left gap / 2
+       //    if (alignment == Align.Right) gapX = gapX;
```
Comment (stephengold) [inline jme3-core/src/main/java/com/jme3/font/Letters.java:248]: Please delete this commented-out code.

File: jme3-core/src/main/java/com/jme3/font/Letters.java [hunk 3]
```diff
@@ -188,42 +194,66 @@ void update() {
...
+                        gapX = 0;
+                    }
                 }
+                cursor.setAlignment(gapX, gapY);
+                cursor = cursor.getPrevious();
+            }
+        } else { // right to left
+            if ((alignment == Align.Right && valignment == VAlign.Top)) return;
+            LetterQuad cursor = tail.getPrevious();
+            gapX = (cursor.getX0()-block.getTextBox().x)*-1;
```
Comment (stephengold) [inline jme3-core/src/main/java/com/jme3/font/Letters.java:246]: Please use unary minus instead of `*-1`

File: jme3-core/src/main/java/com/jme3/font/Letters.java [hunk 4]
```diff
@@ -188,42 +194,66 @@ void update() {
...
+            if (alignment == Align.Center) gapX = gapX/2; // left gap / 2
+       //    if (alignment == Align.Right) gapX = gapX;
+            while (!cursor.isHead()) {
+               if (cursor.isEndOfLine()) {
+                   gapX = (cursor.getX0()-block.getTextBox().x)*-1; // new gapX
```
Comment (stephengold) [inline jme3-core/src/main/java/com/jme3/font/Letters.java:251]: Please use unary minus instead of `*-1`

File: jme3-core/src/main/java/com/jme3/font/Letters.java [hunk 5]
```diff
@@ -232,7 +262,7 @@ private void lineWrap(LetterQuad l) {
             return;
         l.getPrevious().setEndOfLine();
         l.invalidate();
-        l.update(block); // TODO: update from l
+        l.update(block); // TODO: update from l    // --> whats does this mean ? Update from left done ! but from l ???
```
Comment (stephengold) [inline jme3-core/src/main/java/com/jme3/font/Letters.java:265]: Please delete this comment.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java [hunk 6]
```diff
@@ -32,34 +32,67 @@
...
 /**
  * Test case for JME issue #1158: BitmapText right to left line wrapping not work
  */
 public class TestRtlBitmapText extends SimpleApplication {
 
     // A right to left text.
-    final private String text = ".text left to right test a is This";
+    private String text = " check check check linelenght all for  possible .text left to right test a is This";
+    String text2 = "to right test a is This text left.";
+    BitmapFont fnt;
```
Comment (stephengold) [inline jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java:47]: Please declare these fields `private`.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java [hunk 7]
```diff
@@ -32,34 +32,67 @@
...
+
 
     public static void main(String[] args) {
         TestRtlBitmapText app = new TestRtlBitmapText();
         app.start();
     }
-
+    BitmapText txt;
```
Comment (stephengold) [inline jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java:54]: Please move this declaration above the constructor and declare the field `private`.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java [hunk 8]
```diff
@@ -32,34 +32,67 @@
...
     @Override
     public void simpleInitApp() {
-        BitmapFont fnt = assetManager.loadFont("Interface/Fonts/Default.fnt");
+        float H = 500;
+        float X = 400;
```
Comment (stephengold) [inline jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java:58]: Names of local variables should begin with a lowercase letter.

File: local.properties [hunk 9]
```diff
@@ -1 +1,8 @@
-sdk.dir=C:\\AndroidSDK
\ No newline at end of file
+## This file must *NOT* be checked into Version Control Systems,
+# as it contains information specific to your local configuration.
+#
+# Location of the SDK. This is only used by Gradle.
+# For customization when using a Version Control System, please read the
+# header note.
+#Tue Oct 16 13:21:29 CEST 2021
+sdk.dir=C\:\\Users\\Win7Pro64\\AppData\\Local\\Android\\Sdk
```
Comment (stephengold) [inline local.properties:8]: This PR should not change "local.properties". Please revert the changes.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java [hunk 10]
```diff
@@ -32,34 +32,67 @@
...
+    int i =35;
+    float d = 0;
+    @Override
+    public void simpleUpdate(float tpf) {
+ //       BitmapCharacter c = fnt.getCharSet().getCharacter(i);
+ //       c.getKerning(i+1);
+ //       i++;
+  //      txt.setLocalTranslation(d ,300,0);
+  //      d += + 1.01f*tpf;
+   //     System.out.println(cam.getHeight() / 2);
```
Comment (stephengold) [inline jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java:96]: Please delete the commented-out code.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java [hunk 11]
```diff
@@ -32,34 +32,67 @@
...
+
+        txt.setLocalTranslation(X, H, 0);
+        txt.setColor(new ColorRGBA(ColorRGBA.Blue));
         guiNode.attachChild(txt);
+
+        BitmapText txt2 = new BitmapText(fnt);
+        txt2.setBox(new Rectangle(0, 0, 150, 0));
+        txt2.setLineWrapMode(LineWrapMode.Word);
+        txt2.setAlignment(BitmapFont.Align.Left);
+    //    txt2.setVerticalAlignment(BitmapFont.VAlign.Top);
```
Comment (stephengold) [inline jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java:78]: Please delete the commented-out code.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java [hunk 12]
```diff
@@ -32,34 +32,67 @@
...
+
+        txt2.setText(text2);
+        txt2.setLocalTranslation(X,H + 200, 0);
+
+        guiNode.attachChild(txt2);
+
+
+    }
+    int i =35;
+    float d = 0;
```
Comment (stephengold) [inline jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java:88]: Please make these fields private and move the declarations to above the constructor.

**Review by stephengold — CHANGES_REQUESTED** [review]
I want to get this PR integrated before beta, and I don't know when @pspeed42 is going to get a chance to look at it, so did a quick pass. If anything's unclear, please discuss.

**Comment by Ali-RS** [comment]
I applied some of the change requests.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 13]
```diff
@@ -88,6 +88,23 @@
 
     private BitmapCharacterSet charSet;
     private Material[] pages;
+    private boolean rightToLeft = false;
+    // For cursive bitmap fonts (e.g. RTL fonts) in which
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 14]
```diff
@@ -88,6 +88,23 @@
 
     private BitmapCharacterSet charSet;
     private Material[] pages;
+    private boolean rightToLeft = false;
+    // For cursive bitmap fonts (e.g. RTL fonts) in which
+    // letter shape changes depending on its position
+    private GlyphParser glyphParser;
+
+    public boolean isRightToLeft() {
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:99]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 15]
```diff
@@ -88,6 +88,23 @@
...
+
+    public boolean isRightToLeft() {
+        return rightToLeft;
+    }
+
+    // setting the parameter with the font will change it for all!! texts using the font
+    // the parameter is applied by simply using public BitmapText(BitmapFont font)
+    // it can be "overwritten" by using the available public BitmapText(BitmapFont font, boolean rightToLeft)
+    // This way one fnt can be used LtR and RtL in one application
+    public void setRightToLeft(boolean rightToLeft) {
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:107]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 16]
```diff
@@ -88,6 +88,23 @@
...
+    // For cursive bitmap fonts (e.g. RTL fonts) in which
+    // letter shape changes depending on its position
+    private GlyphParser glyphParser;
+
+    public boolean isRightToLeft() {
+        return rightToLeft;
+    }
+
+    // setting the parameter with the font will change it for all!! texts using the font
+    // the parameter is applied by simply using public BitmapText(BitmapFont font)
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 17]
```diff
@@ -123,7 +140,14 @@ public int getPageSize() {
     public BitmapCharacterSet getCharSet() {
         return charSet;
     }
-    
+
+    public void setGlyphParser(GlyphParser glyphParser) {
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:151]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 18]
```diff
@@ -208,6 +232,11 @@ public float getLineWidth(CharSequence text){
         boolean firstCharOfLine = true;
 //        float sizeScale = (float) block.getSize() / charSet.getRenderedSize();
         float sizeScale = 1f;
+
+        if (glyphParser != null) {
+            text = glyphParser.parse(text);
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 19]
```diff
@@ -230,25 +259,37 @@ public float getLineWidth(CharSequence text){
...
+                    }
                     firstCharOfLine = false;
                 }
                 float xAdvance = c.getXAdvance() * sizeScale;
-                
-                // If this is the last character, then we really should have
-                // only added its width.  The advance may include extra spacing
+
+                // If this is the last character of a line, then we really should
+                // have only add its width. The advance may include extra spacing
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java [hunk 20]
```diff
@@ -230,25 +259,37 @@ public float getLineWidth(CharSequence text){
...
                 // that we don't care about.
-                if (i == text.length() - 1) {
-                    lineWidth += c.getWidth() * sizeScale;
- 
-                    // Since the width includes the xOffset then we need
-                    // to take it out again by adding it, ie: offset the width
-                    // we just added by the appropriate amount.
-                    lineWidth += c.getXOffset() * sizeScale;                      
+                if (i == text.length() - 1 || text.charAt(i + 1) == '\n') {
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java]: Well, yes, to be compatible with BitmapText.getLineWidth().

**Comment by Ali-RS** [comment]
I have implemented GlyphParser for Persian text, should we include it in the repo?

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:107]: Should we deprecate `BitmapText(BitmapFont font, boolean rightToLeft)`?

**Comment by stephengold** [comment]
> I have implemented GlyphParser for Persian text, should we include it in the repo as well?

Language-specific features seem like the sort of thing that should be in https://github.com/jMonkeyEngine-Contributions or at the JmonkeyStore, not jme3-core.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (stephengold) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:107]: Is there a reason to deprecate it?

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java (hunk 17 above)
[the remark this answers is not in the document]
Comment (stephengold) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:151]: Great!

File: jme3-core/src/main/java/com/jme3/font/GlyphParser.java [hunk 21]
```diff
@@ -0,0 +1,15 @@
+package com.jme3.font;
```
Comment (stephengold) [inline jme3-core/src/main/java/com/jme3/font/GlyphParser.java:1]: This file needs a BSD license.

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:107]: Well, the correct place is to set the flag in the BitmapFont, otherwise BitmapFont.getLineWidth() might return a wrong result.

File: jme3-core/src/main/java/com/jme3/font/GlyphParser.java (hunk 21 above)
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/GlyphParser.java:1]: My bad! Going to add it. 
Thanks

Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/GlyphParser.java:32]: Fixed.

**Comment by Ali-RS** [comment]
Should "GlyphParser" interface extends `com.jme3.export.Savable`?

**Comment by stephengold** [comment]
> Should "glyphParser" field in the BitmapFont be serialized as well?

I think if the font got saved for some reason, you'd want to serialize the parser as well. So yes.

It might be okay not to clone the glyphParser, however, at least if you document that detail.

**Comment by Ali-RS** [comment]
Want to mention one morething here, that's about using numbers inside RTL text (bidirectional text).
The numbers will be shown in reverse (e.g 123 will be displayed 321).

Swing uses Unicode Bidirectional Algorithm to handle RTL mixed with LTR text. In the case of JME, I managed to fix this issue inside the glyph parser simply by reversing the numbers.

**Comment by stephengold** [comment]
Seems worth documenting in a comment somewhere. Probably in `GlyphParser`.

**Comment by Ali-RS** [comment]
>I think if the font got saved for some reason, you'd want to serialize the parser as well. So yes.

Done.

>Seems worth documenting in a comment somewhere. Probably in GlyphParser.

I will document this inside the PersianGlyphParser implementation, which I will add it to [jMonkeyEngine-Contributions page](https://github.com/jMonkeyEngine-Contributions) later. Then I will add a link to it inside GlyphParser interface. Like this:

>For an example implementation see [link to PersianGlyphParser].

**Comment by stephengold** [comment]
Sorry, I can't follow that link. Retry?

File: jme3-core/src/main/java/com/jme3/font/BitmapFont.java (hunk 15 above)
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/BitmapFont.java:107]: Done.

**Comment by Ali-RS** [comment]
Deprecated the `Deprecate BitmapText(BitmapFont font, boolean rightToLeft)`.

**Comment by Ali-RS** [comment]
I noticed setting text horizontal alignment to the `Right`does not work when vertical alignment is set to anything other than `Top`. That is because the check here is not sufficient (does not consider `Align.Right`): 
https://github.com/Aufricer/jmonkeyengine/blob/f2f39b369e1bb9da3acb6226d784bc581a394cc3/jme3-core/src/main/java/com/jme3/font/Letters.java#L252

I will submit a patch to fix it and other change requests.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java (hunk 12 above)
Comment (Ali-RS) [reply jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java]: Fixed.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java (hunk 11 above)
Comment (Ali-RS) [reply jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java]: Fixed.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java (hunk 10 above)
Comment (Ali-RS) [reply jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java]: Fixed.

File: local.properties (hunk 9 above)
Comment (Ali-RS) [reply local.properties]: Fixed.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java (hunk 8 above)
Comment (Ali-RS) [reply jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/LetterQuad.java [hunk 22]
```diff
@@ -347,44 +356,69 @@ void update(StringBlock block) {
...
+                   // to take kerning into account below... which will also
+                   // get baked in.
+                   // Without this, getNextX() will return values too far to
+                   // the left, for example.
+                   xAdvance -= xOffset * incrScale;
+                }
             }
             y0 = lineY + LINE_DIR*yOffset;
 
-            // Adjust for kerning
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/LetterQuad.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/Letters.java (hunk 1 above)
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/Letters.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/Letters.java (hunk 2 above)
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/Letters.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/Letters.java (hunk 3 above)
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/Letters.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/Letters.java (hunk 4 above)
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/Letters.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/Letters.java (hunk 5 above)
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/Letters.java]: Fixed.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java (hunk 6 above)
Comment (Ali-RS) [reply jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java]: Fixed.

File: jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java (hunk 7 above)
Comment (Ali-RS) [reply jme3-examples/src/main/java/jme3test/gui/TestRtlBitmapText.java]: Fixed.

File: jme3-core/src/main/java/com/jme3/font/LetterQuad.java [hunk 23]
```diff
@@ -170,7 +170,12 @@ boolean isInvalid(StringBlock block, float gap) {
         if (bound == null) {
             return false;
         }
-        return x0 > 0 && bound.x+bound.width-gap < getX1();
+        if (isRightToLeft()) {
+            return x0 <0 && x0<bound.x;
+            // ToDo check for ellipsis, not sure if it is on both sides of a character and need to be deducted as well
```
[the remark this answers is not in the document]
Comment (Ali-RS) [reply jme3-core/src/main/java/com/jme3/font/LetterQuad.java:175]: @Aufricer any idea?

**Comment by Ali-RS** [comment]
This is the GlyphParser implementation for Persian text:
https://github.com/Ali-RS/JME-PersianGlyphParser/blob/f162ac7a248683553792751e024485ec8e3aec34/src/main/java/com/jme3/font/plugins/PersianGlyphParser.java#L47

**Comment by Ali-RS** [comment]
>Then I will add a link to it inside GlyphParser interface.
Like this: "For an example implementation see [link to PersianGlyphParser]."

Done

File: jme3-core/src/main/java/com/jme3/font/LetterQuad.java (hunk 23 above)
[the remark this answers is not in the document]
Comment (stephengold) [reply jme3-core/src/main/java/com/jme3/font/LetterQuad.java:175]: I don't want to delay beta, so it'll have to be later, if at all.

**Comment by stephengold** [comment]
I believe this is ready for integration.

Unless there's further discussion, I plan to fix a few stylistic issues and integrate this in about 24 hours.

**Review by stephengold — APPROVED** [review]

**Comment by stephengold** [comment]
The "local.properties" file will soon be addressed by PR #1708.

**Comment by Ali-RS** [comment]
Thanks, @stephengold :)

**Comment by stephengold** [comment]
Thanks, @Aufricer and @Ali-RS!
