### PR TITLE
When in VR attach the debug scene to the two eye's scenes. Fix #1795 

### LINKED ISSUE #1795: BulletAppState debug not working in VR
Hello.

A BulletAppState has a nice `bulletAppState.setDebugEnabled(true);` really handy to debug physics. Unfortunately, it doesn't work in VR. Below is a reproductive test case. It's the VR example from the wiki, with 1/ A bullet app state 2/ a green cube, not a blue one, because bullet wireframe view is either pink-ish or blue.

```
public class MainVRxBulletDebugBug  extends SimpleApplication {

    public static void main(String[] args) {
        AppSettings settings = new AppSettings(true);
        settings.put(VRConstants.SETTING_VRAPI, VRConstants.SETTING_VRAPI_OPENVR_LWJGL_VALUE);
        settings.put(VRConstants.SETTING_ENABLE_MIRROR_WINDOW, true);

        VREnvironment env = new VREnvironment(settings);
        env.initialize();

    	// Checking if the VR environment is well initialized
    	// (access to the underlying VR system is effective, VR devices are detected).
    	if (env.isInitialized()){
            VRAppState vrAppState = new VRAppState(settings, env);
            vrAppState.setMirrorWindowSize(1024, 800);
            MainVRxBulletDebugBug app = new MainVRxBulletDebugBug(vrAppState, new BulletAppState());
            app.setLostFocusBehavior(LostFocusBehavior.Disabled);
            app.setSettings(settings);
            app.setShowSettings(false);
            app.start();
        }
    }

    public MainVRxBulletDebugBug(AppState... appStates) {
        super(appStates);
    }

    @Override
    public void simpleInitApp() {
        BulletAppState bulletAppState = getStateManager().getState(BulletAppState.class);
        bulletAppState.getPhysicsSpace().setGravity(new Vector3f(0, 2f, 0));
        bulletAppState.setDebugEnabled(true);
        
        Box b = new Box(1, 1, 1);
        Geometry geom = new Geometry("Box", b);

        Material mat = new Material(assetManager, "Common/MatDefs/Misc/Unshaded.j3md");
        mat.setColor("Color", ColorRGBA.Green);
        geom.setMaterial(mat);
        
        RigidBodyControl rigidBodyControl = new RigidBodyControl(1.0f);
        geom.addControl(rigidBodyControl);
        bulletAppState.getPhysicsSpace().add(rigidBodyControl);

        rootNode.attachChild(geom);
    }

}
```

### PR DESCRIPTION
**Pull request by richardTingle**
This ensures they show up correctly, as the VRAppState uses totally separate cameras and viewports to the normal JME flow

Resolves issue [#1795](https://github.com/jMonkeyEngine/jmonkeyengine/issues/1795)

### CODE REVIEW

**Comment by Ali-RS** [comment]
@richardTingle thanks for your contribution.

Can you please fix the formatting issues? 
Add white a space in `){` and `try{`

**Comment by richardTingle** [comment]
Sure @Ali-RS, done

File: jme3-jbullet/src/main/java/com/jme3/bullet/debug/BulletDebugAppState.java [hunk 1]
```diff
@@ -413,4 +434,17 @@ public static interface DebugAppStateFilter {
          */
         public boolean displayObject(Object obj);
     }
-}
+
+    private boolean isVr(){
```
Comment (Ali-RS) [inline jme3-jbullet/src/main/java/com/jme3/bullet/debug/BulletDebugAppState.java:438]: Seems `){` is also missing a space.

File: jme3-jbullet/src/main/java/com/jme3/bullet/debug/BulletDebugAppState.java [hunk 2]
```diff
@@ -413,4 +434,17 @@ public static interface DebugAppStateFilter {
...
+        if (isVr == null) {
+            try {
+                VRAppState vrAppState = app.getStateManager().getState(VRAppState.ID, VRAppState.class);
+                isVr = vrAppState != null && !vrAppState.DISABLE_VR;
+            } catch(NoClassDefFoundError e) {
```
Comment (Ali-RS) [inline jme3-jbullet/src/main/java/com/jme3/bullet/debug/BulletDebugAppState.java:443]: Add space also in `catch(`

**Comment by Ali-RS** [comment]
Thanks

**Comment by richardTingle** [comment]
> Unless there's substantial discussion, I plan to integrate this in about 24 hours.

Not sure if you saw, but in the related issue https://github.com/jMonkeyEngine/jmonkeyengine/issues/1795 [stephengold](https://github.com/stephengold) mentioned that he is happy for these changes to be integrated.

Based on conversation in 1795 I've added a comment on why the VR and non-VR implementations are so different "This is a less good solution than the non-vr version (as the debug shapes can be obscured by the regular geometry), however it is the best possible as VR does not currently support multiple viewports per eye"
