### PR TITLE
Fix TextureArray not exporting WrapMode

### LINKED ISSUE #2394: TextureArray not exporting WrapMode
The TextureArray class does not implement write() and read() and so when it is exported to .j3o and read back it does no longer wrap in the same way as originally set.
I compared with Texture2D and that one does implement these methods.
I will submit a PR with this change.

### PR DESCRIPTION
**Pull request by jcfandino**
Fixes #2394

### CODE REVIEW

File: jme3-core/src/test/java/com/jme3/texture/TextureArrayTest.java [hunk 1]
```diff
@@ -0,0 +1,42 @@
+package com.jme3.texture;
```
Comment (stephengold) [inline jme3-core/src/test/java/com/jme3/texture/TextureArrayTest.java:1]: Please add a copy of the JME license.

Comment (jcfandino) [reply jme3-core/src/test/java/com/jme3/texture/TextureArrayTest.java:32]: Done!

File: jme3-core/src/main/java/com/jme3/texture/TextureArray.java [hunk 2]
```diff
@@ -151,4 +156,41 @@ public void setWrap(WrapMode mode) {
...
+    @Override
+    public void read(JmeImporter importer) throws IOException {
+        super.read(importer);
+        InputCapsule capsule = importer.getCapsule(this);
+        wrapS = capsule.readEnum("wrapS", WrapMode.class, WrapMode.EdgeClamp);
+        wrapT = capsule.readEnum("wrapT", WrapMode.class, WrapMode.EdgeClamp);
+    }
+
+    @Override
+    public boolean equals(Object other) {
```
Comment (yaRnMcDonuts) [inline jme3-core/src/main/java/com/jme3/texture/TextureArray.java:177]: The equals() method just needs updated to include the == check first:

```
       if (this == obj) {
            return true; 
        }
```

Otherwise everything looks good with the PR and it should be ready to merge after this change.

Comment (jcfandino) [reply jme3-core/src/main/java/com/jme3/texture/TextureArray.java:177]: Good catch!
I'll try to fix it as soon as I can.
I might not find the time in the next few days so if you want to make the change quick please go ahead.
thx

Comment (yaRnMcDonuts) [reply jme3-core/src/main/java/com/jme3/texture/TextureArray.java:177]: Sounds good, I've went ahead and made the change for you, so everything should be good and ready to merge now. Thanks for your contribution! 

And I also owe you a second thanks, since reporting this issue also helped me figure out how to properly save my project's Texture Arrays

**Comment by yaRnMcDonuts** [comment]
I made the changes that I requested in my review (with the permission of the PR author) and everything looks good. So I will plan to merge this in ~48 hours.
